In [ ]:
# Numpy
import numpy as np


In [ ]:
my_list = list(range(10000)) # list
my_array = np.arange(10000) # array (massiv)

my_array

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [ ]:
%%time
for i in my_list:
  i*2

# List comprehension
doubled = [i*2 for i in my_list]
doubled

CPU times: user 1.84 ms, sys: 0 ns, total: 1.84 ms
Wall time: 1.84 ms


[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [ ]:
%%time
for _ in range(10):
  my_array*2

CPU times: user 500 µs, sys: 0 ns, total: 500 µs
Wall time: 508 µs


1. Array yaratish

In [ ]:
arr1 = np.array([1.5, 3.6, 82])
arr1

array([ 1.5,  3.6, 82. ])

In [ ]:
data = [1, 2, 4, 6]
arr2 = np.array(data)
arr2

array([1, 2, 4, 6])

In [ ]:
# Tuple
data_tuple = (1, 2, 3)
arr3 = np.array(data_tuple)
arr3

array([1, 2, 3])

1 O-o'lchamli massivlar

In [ ]:
arr1.ndim

1

In [ ]:
arr3.ndim

1

2 va undan ortiq o'lchamlilar

In [ ]:
data3 = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]
arr4 = np.array(data3)
arr4
arr4.ndim

2

Shape size attributes

In [ ]:
arr4.shape

(3, 3)

In [ ]:
arr4.size

9

N o'lchovli massivlarni yaratishning boshqa usullari

In [ ]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ordered = np.arange(0, 100, 2) # Qadamlar soni 2 ga oshishi
ordered

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
ordered2 = np.arange(21)
ordered2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
arr5 = np.random.rand(2, 4) # 2 o'lchamdagi taxminiy qiymatlar topish
arr5

array([[0.92989454, 0.65738656, 0.34967318, 0.59246535],
       [0.93418383, 0.17793421, 0.94865571, 0.01707994]])

In [ ]:
# 2 o'lchamdagi taxminiy qiymatlar topish intqiymatli
arr6 = np.random.randint(5, size = (12, 4))
arr6



array([[0, 4, 4, 0],
       [1, 1, 0, 0],
       [3, 4, 0, 4],
       [2, 2, 4, 0],
       [2, 2, 3, 3],
       [3, 4, 3, 4],
       [2, 1, 0, 3],
       [0, 0, 0, 3],
       [0, 2, 0, 3],
       [0, 4, 4, 2],
       [4, 2, 2, 2],
       [0, 4, 4, 0]])

In [ ]:
# Random olingan qiymatlarni o'zgarmas qilib qo'yish
np.random.seed(42)
arr6

array([[0, 4, 4, 0],
       [1, 1, 0, 0],
       [3, 4, 0, 4],
       [2, 2, 4, 0],
       [2, 2, 3, 3],
       [3, 4, 3, 4],
       [2, 1, 0, 3],
       [0, 0, 0, 3],
       [0, 2, 0, 3],
       [0, 4, 4, 2],
       [4, 2, 2, 2],
       [0, 4, 4, 0]])

In [ ]:
# Ones_like. Hamma elementlarini 0 ga aylantirish
ones_like = np.ones_like(arr6)
ones_like

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
zeros_like = np.zeros_like(arr6)
zeros_like

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# efe, yoki identity yaratsih
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

NumPy kutubxonasi ma'lumot turlar

In [ ]:
# Float64 ma'lumot turi
arr1 = np.array([18, 25, 1.85, 32000], dtype=np.int16)
arr1.dtype
arr1

array([   18,    25,     1, 32000], dtype=int16)

In [ ]:
float_arr = arr1.astype(np.float32)
float_arr

array([1.8e+01, 2.5e+01, 1.0e+00, 3.2e+04], dtype=float32)

N qiymatli datalar

In [ ]:
arr = np.arange(10, 100, 10) # 10 dan 90 gacha
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr[3:5]


array([40, 50])

In [ ]:
# Kesib olish
sliced_arr = arr[3:5]
sliced_arr
sliced_arr[0] = sliced_arr[0*2]
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# arr copy

2D array indeks kesib olish


In [ ]:
arr2d = np.arange(9).reshape(3, 3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr2d[1, 1:3]

array([4, 5])

In [ ]:
arr2d[1:3, 2]


array([5, 8])

In [ ]:
arr2d[2, 0::2] # 2 ta sakratib oshirish

array([6, 8])

NumPy da Broadcasting

In [ ]:
arr = np.random.rand(5, 4)
arr

a = np.arange(12).reshape(2, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
a = np.arange(1, 10).reshape(3,3)
b = np.array([3, 6, 9]).reshape(3, 1)
b.shape
b
a/b


array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])